[package]
name = "auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.4", optional = true }
chrono = { version = "0.4.33", features = ["serde"] }
forgen = { path = "../forgen" }
hmac = { version = "0.12.1", optional = true }
jwt = { version = "0.16.0", optional = true }
mongodb = { version = "2.8.0", default-features = false, features = ["sync"],  optional = true }
regex = "1.10.3"
reqwest = { version = "0.11", features = ["json"],  optional = true }
serde = "1.0.196"
serde_urlencoded = { version = "0.7.1", optional = true }
sha2 = "0.10.8"
urlencoding = { version = "2.1.3", optional = true }
uuid = { version = "1.7.0", features = ["serde", "v4"] }
wasm-bindgen = { version = "0.2.90", optional = true }
web-sys = { version = "0.3.68", optional = true }

[dev-dependencies]
axum-test = "14.3.0"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0.113"
tokio = { version = "1.0", features = ["full"] }

[features]
default = ["jwt", "linkedin"]
axum = ["dep:axum"]
jwt = ["dep:hmac", "dep:jwt"]
mongodb = ["dep:mongodb"]
linkedin = ["dep:reqwest", "dep:serde_urlencoded"]
wasm = ["dep:urlencoding", "dep:wasm-bindgen", "dep:web-sys"]
