[package]
name = "auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.4", optional = true }
framework = { path = "../framework" }
hmac = "0.12.1"
jwt = "0.16.0"
regex = "1.10.3"
serde = "1.0.196"
serde_json = "1.0.113"
sha2 = "0.10.8"
uuid = { version = "1.7.0", features = ["serde", "v4"] }
validator = { version = "0.16.1", features = ["derive"] }

[dev-dependencies]
axum-test = "14.3.0"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0.113"
tokio = { version = "1.0", features = ["full"] }

[features]
default = ["axum"]
axum = ["dep:axum"]
